# Site settings
title: André Iván
email: andre801mz@gmail.com
url: http://andreivan.me/
description: "I’m André Iván. Web Developer, FrontEnd, Backend & UI/UX Designer"
keywords: "your keywords, separated by commas"
meta_author: Iván André

# My collections
collections:
  works:
    output: true
    permalink: /works/:name/


# Polyglot settings
languages: ["en", "es"]
default_lang: "en"

plugins:
  - jekyll-polyglot

social:
  - title: twitter
    url: http://twitter.com/jekyllrb


# Build settings
markdown: kramdown
permalink: pretty
